version: 5.1.0
variant: default
logo: >-
    data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAA3QAAAN0BcFOiBwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAPhSURBVFiFzddvaJVVHAfwz3O7un+uzam11fzzpmLlDKEyy2xYYZowCXyzRVoR9EoxSAjFF+bAN6FEFL2TQqg34V6kvZKVWkgGOoWRhPlndGdaLmdz2929Ty+eu/93e+4WRV84nN89zzm/7/f8zj3n/E4QhqFCEPysSI810hqF6mTUyKiRRUYKKRkdQq0yjoXr9BfkN05A0KFG2m6hZhnlMuRIDdtZhGPsHlmHJOwJ10rNSEBwSbF+u2Rsl1E6gXRqAUN2L/Yrszds0FewgOCSaoMOy1gxKWlhAiKbUxI2hut1xQoIOtVLOyKjdpgkD+mKUjZUsKyMq32c7OaLLrKZPAKi0im0Pmx0blIBwXXV+vxgcBz5KAF3ZXm/lq3VBONmc7Kbpnau3MkrIBIx4PFw00gkEqPCXmzQYdROWJNR2FHNtmpSA7xxgWWn2dDOiW6eruTzZSTGKxtBrVkOBwcVT4hAcN1eaTtlMDhu9rkILAjorKc/yyNnuNo7MtME2pbzTCWbz/FpZ94IRCXQEjbaNRyB4IYaoe1TzRyeKGN2wGc3uDpul2dD3rsY2avmxjgKbQ++VDMsQGA3SuME1JdE9bne/N9/S0f14pI4T0pznBIBRWiOHYLi3Nr2TXJ2vVId1WdvFeJNc3BUUcJNa1Be0JApsLSMLfdF9pEbBQ0p129NEo0zJQ2wrorN97Lpnuj3h1do+6NAB1mNSYG6mQqoL+Or+vE+o3XNFuaiLkn0b5wJzv/FWxeYl6SulOer2LqIxcU0naE3XkXNPxKQxScpw/v97gQfPURzDUceo+H7eAGJ2C7TwK1BXjvP2R6ereKF+fFjEkx9X08X6ZAPLkf2iwtiu6dmJCAubKdz58DC+AMplRTqwOrpCKiLcdzew7s/8e3vsa46EmidDjmsryQ5+Y0H9l3ku5sxjhJaE+Y6hp7pCHi4hJZFk3ybw3PzCnLTo8ixREg/Dk1HAOy4n6+X8tI8FhaxsoIDD9K+ktblU+YEQzgUrtOfBKE9eNW4G/GpElYXs+/a2JEHumgoZ+3cqIzGtQG2dUTX8xTozXFKQjhfKrhuP3aO7rWlgjcrON7DydtUz4raj3bzzi80VfFkOUtLudzHj7c42El3Ombugf3hy9HuG8mILilWpM2gFUMZ0arZHF/ExQHabtNUya9pHjiTSz4LzYrHllO6NYRbojR9eEuHS/RJ2ojOobYTd/j4ZnRgv14Vkb99peCLJh86pW0cIh8TgeGGPGl5FR4t4ps/czOf7rug0LR8uPE/fJjkPVXDJbokNaAFk2SABaFXoMUcDfnI+T8/Tid0/Jee538DCU7yqteQR9kAAAAASUVORK5CYII=
head:
    favicon: >-
        /assets/favicon.png
    meta:
        - ''
    rss: 
navbar:
    menu:
        首页: /
        文章列表: /archives
        分类: /categories
        标签: /tags
        关于: /about
    links:
        GitHub:
            icon: fab fa-github
            url: https://github.com/luoweihua7
footer:
    links:
        粤ICP备20055631号:
            icon: ''
            url: https://beian.miit.gov.cn/
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: false
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        CC BY-NC-SA 4.0: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
search:
    type: insight
sidebar:
    left:
        sticky: true
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: Larify
        author_title: 前端开发工程师
        location: 中国
        avatar: https://avatars.githubusercontent.com/u/3157520
        avatar_rounded: true
    -
        position: left
        type: toc
        index: true
        collapsed: false
        depth: 3
    -
        position: left
        type: categories
    -
        position: left
        type: recent_posts
    -
        position: left
        type: archives
    -
        position: left
        type: tags
        order_by: name
        amount: 
        show_count: true
plugins:
    animejs: false
    back_to_top: true
    baidu_analytics:
        tracking_id: 8ded3b97800309f7a340445c8c13d3b0
    cookie_consent:
        type: info
        theme: classic
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: G-XF11D6Z7R2
    katex: false
    mathjax: false
    outdated_browser: true
    progressbar: true
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
